version: "3.1"

services:

  mongo:
    image: mongo
    container_name: "mongo-weatherApp"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: weatherApp
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo/data:/data/db

  weather_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGOHOST: mongo
      MONGOUSER: weatherApp
      MONGOPASS: root
      APIKEY: d3d638de1287cea2ee25cd7faaaef7c5