version: "3.1"

services:

  mongo:
    image: mongo
    container_name: "mongo-test"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: weatherApp
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db